frr version 10.2.1
frr defaults traditional
hostname as65005
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65005
 bgp router-id 10.0.25.3
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 timers bgp 3 9
 !
 neighbor 10.0.25.2 remote-as 65002
 neighbor 10.0.25.2 description Peering-to-AS65002
 !
 address-family ipv4 unicast
  neighbor 10.0.25.2 activate
  neighbor 10.0.25.2 send-community both
  neighbor 10.0.25.2 route-map RM_IN_AS65002 in
 exit-address-family
exit
!
route-map RM_IN_AS65002 permit 10
 set local-preference 100
exit
!
line vty
exit
