frr version 10.2.1
frr defaults traditional
hostname as65004
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65004
 bgp router-id 10.0.14.3
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 timers bgp 3 9
 !
 neighbor 10.0.14.2 remote-as 65001
 neighbor 10.0.14.2 description Peering-to-AS65001
 neighbor 10.0.49.3 remote-as 65009
 neighbor 10.0.49.3 description Peering-to-AS65009
 !
 address-family ipv4 unicast
  neighbor 10.0.14.2 activate
  neighbor 10.0.14.2 send-community both
  neighbor 10.0.14.2 route-map RM_IN_AS65001 in
  neighbor 10.0.49.3 activate
  neighbor 10.0.49.3 send-community both
  neighbor 10.0.49.3 route-map RM_IN_AS65009 in
 exit-address-family
exit
!
route-map RM_IN_AS65001 permit 10
 set local-preference 100
exit
!
route-map RM_IN_AS65009 permit 10
 set local-preference 100
exit
!
line vty
exit
