frr version 10.2.1
frr defaults traditional
hostname as65010
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65010
 bgp router-id 10.0.60.3
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 timers bgp 3 9
 !
 neighbor 10.0.60.2 remote-as 65006
 neighbor 10.0.60.2 description Peering-to-AS65006
 !
 address-family ipv4 unicast
  neighbor 10.0.60.2 activate
  neighbor 10.0.60.2 send-community both
  neighbor 10.0.60.2 route-map RM_IN_AS65006 in
 exit-address-family
exit
!
route-map RM_IN_AS65006 permit 10
 set local-preference 100
exit
!
line vty
exit
