frr version 10.2.1
frr defaults traditional
hostname as65007
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 192.0.2.1/24
exit
!
router bgp 65007
 bgp router-id 10.0.37.3
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 timers bgp 3 9
 !
 neighbor 10.0.37.2 remote-as 65003
 neighbor 10.0.37.2 description Peering-to-AS65003
 !
 address-family ipv4 unicast
  network 192.0.2.0/24
  neighbor 10.0.37.2 activate
  neighbor 10.0.37.2 send-community both
  neighbor 10.0.37.2 route-map RM_IN_AS65003 in
 exit-address-family
exit
!
route-map RM_IN_AS65003 permit 10
 set local-preference 100
exit
!
line vty
exit
