frr version 10.2.1
frr defaults traditional
hostname as65003
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 65003
 bgp router-id 10.0.13.3
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 timers bgp 3 9
 !
 neighbor 10.0.13.2 remote-as 65001
 neighbor 10.0.13.2 description Peering-to-AS65001
 neighbor 10.0.37.3 remote-as 65007
 neighbor 10.0.37.3 description Peering-to-AS65007
 neighbor 10.0.38.3 remote-as 65008
 neighbor 10.0.38.3 description Peering-to-AS65008
 !
 address-family ipv4 unicast
  neighbor 10.0.13.2 activate
  neighbor 10.0.13.2 send-community both
  neighbor 10.0.13.2 route-map RM_IN_AS65001 in
  neighbor 10.0.37.3 activate
  neighbor 10.0.37.3 send-community both
  neighbor 10.0.37.3 route-map RM_IN_AS65007 in
  neighbor 10.0.38.3 activate
  neighbor 10.0.38.3 send-community both
  neighbor 10.0.38.3 route-map RM_IN_AS65008 in
 exit-address-family
exit
!
route-map RM_IN_AS65001 permit 10
 set local-preference 100
exit
!
route-map RM_IN_AS65007 permit 10
 set local-preference 100
exit
!
route-map RM_IN_AS65008 permit 10
 set local-preference 100
exit
!
line vty
exit
